maps:
  api_key: <GOOGLE-JS-MAPS-API-KEY>
  lat: 11.380155
  lng: 75.722381
destinations:
  android: adb shell am broadcast -a send.mock -e lat :lat -e lon :lng
  ios: set-simulator-location -c :lat :lng
